### ISSUE TITLE
✨ [Feature] 문자열 검증 1: '/', ' / ' 2개 검증

### ISSUE THREAD

**Issue by vanism2091** [SunnnySong/ios-cantact-manager#1]
## 설명: **Is your feature request related to a problem? Please describe.**
입력받은 문자열에 '/', ' / ' 이 2개 있는지 확인한다.

## 솔루션: **Describe the solution you'd like**
- components로 '/' 또는 ' / '로 입력받은 나눈 후
- list의 길이 count로 체크한다

## To-do
- [ ] string에 ' / '이 있는지 체크
- [ ] 있다면, ' / '로 split 후 길이 확인
- [ ] 없다면, '/'로 split 후 길이 확인
- [ ] 길이가 3이면 올바른 입력
- [ ] 그렇지 않으면 올바르지 않은 입력

## 기타 사항: **Additional context**
"[이름] / [나이]/[연락처]" 처럼, seperator가 동일하지 않은 경우, 
올바르지 않은 입력으로 판단할지 아닐지 대화를 나누었고
올바르지 않은 입력으로 판단하기로 결정했다!
