### ISSUE TITLE
✨ [Feature] 문자열 검증 2: 이름

### ISSUE THREAD

**Issue by vanism2091** [SunnnySong/ios-cantact-manager#3]
## 설명: **Is your feature request related to a problem? Please describe.**
입력 문자열 중 이름을 검증한다

## 솔루션: **Describe the solution you'd like**
정규식을 이용한다.
입력받은 이름에 띄어쓰기가 있다면 없앤다.
올바르지 않은 입력이면 에러를 뱉는다.

## To-do
- [ ] 이름을 검증할 정규식을 작성한다.
- [ ] 이름을 검증한 후 올바른 입력일 때, 빈칸이 있으면 지운다
- [ ] 올바르지 않은 입력이라면 에러를 뱉는다

## 기타 사항: **Additional context**
영어만 허용할지 숫자만 허용할지 대화함
- 영어만 허용하는 걸로 결정
