### ISSUE TITLE
✨ [Feature] Error 정의 및 String 구현 

### ISSUE THREAD

**Issue by SunnnySong** [SunnnySong/ios-cantact-manager#7]
## 설명: **Is your feature request related to a problem? Please describe.**
Error를 정의하고 Error 별 String을 구현. 

## 솔루션: **Describe the solution you'd like**
Enum으로 Error case를 정의하고, case 별 String 을 구현한다. 

## To-do
- [ ] Error 파일을 생성한다.
- [ ] Error case를 정의한다. 
- [ ] Error 별 String을 구현한다.
